// <auto-generated />
namespace InventoryDash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_togos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_togos));
        
        string IMigrationMetadata.Id
        {
            get { return "201706281747278_add_togos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
